name: Run Tests and Publish Allure Report

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        python -m playwright install
        npm install -g allure-commandline --save-dev

    - name: Run tests with Allure
      run: |
        pytest --alluredir=allure-results

    - name: Generate Allure Report
      run: |
        allure generate allure-results -o allure-report --clean

    - name: Apply custom styles to Allure Report
      run: |
        cp allure-custom/styles.css allure-report/custom.css
        sed -i '/<head>/a <link rel="stylesheet" href="custom.css">' allure-report/index.html

    - name: Deploy Allure Report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: allure-report
        publish_branch: gh-pages